# Generated by Django 6.0.4 on 2026-04-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='player2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='score1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='score2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
