# Generated by Django 6.0.4 on 2026-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sala_player2_alter_sala_score1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='letra',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
