# Generated by Django 6.0.4 on 2026-04-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sala_letra'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='mensaje',
            field=models.TextField(blank=True, max_length=1, null=True),
        ),
    ]
